### ISSUE TITLE
Table of miRNA family conservation in 27 insect species

### ISSUE THREAD

**Issue by mt1022** [vagarwal87/TargetScanTools#1]
Dear Dr. Vikram Agarwal,

Hi. I noticed that you have complied a table of miRNA conservation as described in your paper:

> Towards this end, we compiled miRNA annotations from multiple studies [8, 10, 11, 15] and classified 91 miRNA families as broadly conserved among Drosophila species, 29 of which have been conserved since the last bilaterian ancestor (Additional file 4: Table S3). 

However, I only found a list of names of the 91 conserved miRNAs. I am wondering whether you have a table of miRNA family presence/absence in the 27 insect species that are used for conservation analysis. Since targetScanFly 7.2 requires a miRNA family info file in the following format:
```
bantam-3p	GAGAUCA	7070;7165;7217;7220;7222;7227;...;1041015
let-7-5p	GAGGUAG	7070;7165;7217;7220;7222;7227;...;1041015
miR-1-3p	GGAAUGU	7070;7165;7217;7220;7222;7227;...;1041015
miR-79-5p	CUUUGGC	7227;7244
```
, such a table would be helpful for users like me or others who want to predict conserved targets for custom set of transcripts that are not selected as representative transcripts.

Thanks in advance.

Best regards.

**Comment by vagarwal87** [comment]
Hi, Thanks for your interest in TargetScan! I'll try to get these for you in the next day or two from the Whitehead Bioinformatics team...I believe we already have these somewhere.

**Comment by vagarwal87** [comment]
Hi, The file you requested is now downloadble as miR_Family_info.txt in: http://www.targetscan.org/fly_72/fly_72_data_download/targetscan_70_BL_PCT.zip and http://www.targetscan.org/fly_72/fly_72_data_download/TargetScan7_context_scores.zip

They are slightly different file formats, with the latter being similar to the one you mentioned above.

Good luck!
