### ISSUE TITLE
How to create the UTR-alignment file for TargetScan

### ISSUE THREAD

**Issue by jonbra** [vagarwal87/TargetScanTools#2]
I want to run TargetScan on a non-model organism. I have transcriptomes of closely related species. Any advice on how to best create the UTR-alignment and format it correctly to use with TargetScan? 

Thanks!

Jon

**Comment by vagarwal87** [comment]
Hi Jon,

To my knowledge we generally have only used precomputed multiz alignments in the past as input. I imagine the best way might be to run multiz with the same parameters as that done by the UCSC genome browser on your personal species, then use mafFrag to extract the relevant coordinates.

If you get stuck in generating them in the correct format, I suggest you email barc@wi.mit.edu for additional info to see if the Whitehead Bioinformatics core facility has scripts or procedures to generate them.

Hope that helps a bit! 

Best,
Vikram
